# Generated by Django 4.2.2 on 2023-06-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_info', '0002_alter_municipality_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country_info.province'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country_info.district'),
        ),
    ]
