# Generated by Django 4.2.2 on 2023-06-07 09:06

from utils.file_rename import File
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True,
                 null=True, upload_to=File('account/').rename)),
                ('verified', models.CharField(choices=[
                 ('V', 'Verified'), ('U', 'Unverified')], default='U', max_length=300)),
                ('role', models.OneToOneField(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='account.userrole')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
