# Generated by Django 4.2.2 on 2023-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='verified',
            new_name='verification_status',
        ),
    ]
