# Generated by Django 4.2.2 on 2023-06-07 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_rename_verified_userprofile_verification_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfileModel',
        ),
        migrations.RenameModel(
            old_name='UserRole',
            new_name='UserRoleModel',
        ),
    ]
