# Generated by Django 4.2.2 on 2023-06-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_userprofile_userprofilemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('D', 'Driver'), ('H', 'Household User')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='verification_status',
            field=models.CharField(choices=[('V', 'Verified'), ('U', 'Unverified')], default='U', max_length=1),
        ),
        migrations.DeleteModel(
            name='UserRoleModel',
        ),
    ]
