# Generated by Django 4.2.2 on 2023-06-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_info', '0003_alter_district_province_alter_municipality_district'),
        ('account', '0004_alter_userprofilemodel_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='country_info.municipality'),
        ),
    ]
