# Generated by Django 4.2.2 on 2023-06-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_collectionpoint_collection_route_and_more'),
        ('account', '0005_userprofilemodel_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='colection_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.collectionroute'),
        ),
    ]
