# Generated by Django 4.2.2 on 2023-06-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofilemodel_colection_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='colection_route',
            new_name='collection_route',
        ),
    ]
