# Generated by Django 4.2.2 on 2023-06-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_colection_route_userprofilemodel_collection_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCollectionMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_mode', models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0)),
            ],
        ),
    ]
