# Generated by Django 4.2.2 on 2023-09-07 12:13

from django.db import migrations, models
from utils.file_rename import File


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_drivercollectionmode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('image', models.ImageField(upload_to=File('test/'))),
            ],
        ),
    ]
