# Generated by Django 4.2.2 on 2023-09-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_testimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
