# Generated by Django 4.2.2 on 2023-09-27 10:00

from django.db import migrations, models
import utils.file_rename


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_testimage_image_alter_userprofilemodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='image',
            field=models.ImageField(upload_to=utils.file_rename.File.rename),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_rename.File.rename),
        ),
    ]
