# Generated by Django 4.2.2 on 2023-10-01 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_on', models.DateTimeField(auto_created=True)),
                ('refresh_count', models.PositiveIntegerField(default=0)),
                ('token', models.CharField(max_length=500)),
                ('platform', models.PositiveSmallIntegerField(choices=[(0, 'Android'), (1, 'IoS'), (2, 'Web'), (3, 'Windows'), (4, 'MacOS'), (5, 'LINUX')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
