# Generated by Django 4.2.2 on 2023-10-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_device_platform_alter_device_registered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='registered_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
