# Generated by Django 4.2.2 on 2023-06-11 10:30

from django.db import migrations, models
from utils.file_rename import File


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('waste_volume', models.DecimalField(
                    decimal_places=6, max_digits=9)),
                ('waste_nature', models.SmallIntegerField(choices=[
                 (1, 'Organic'), (2, 'Plastic'), (3, 'Glass'), (4, 'Debris')], default=1)),
                ('image', models.ImageField(blank=True, null=True,
                 upload_to=File('waste/').rename)),
                ('waste_for', models.SmallIntegerField(choices=[
                 (1, 'On Demand Waste'), (1, 'Waste for Money')], default=0)),
            ],
        ),
    ]
