# Generated by Django 4.2.2 on 2023-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='waste_for',
            field=models.SmallIntegerField(choices=[(0, 'On Demand Waste'), (1, 'Waste for Money')], default=0),
        ),
    ]
