# Generated by Django 4.2.2 on 2023-06-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_waste_waste_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='collection_status',
            field=models.SmallIntegerField(choices=[(0, 'Collected'), (1, 'Remain to Collect')], default=1),
        ),
    ]
