# Generated by Django 4.2.2 on 2023-09-26 14:21

from django.db import migrations, models
import utils.file_rename


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_waste_collection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_rename.File.rename),
        ),
        migrations.AlterField(
            model_name='waste',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='waste',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
