# Generated by Django 4.2.2 on 2023-09-27 10:00

from django.db import migrations, models
import utils.file_rename


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_alter_waste_image_alter_waste_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_rename.File.rename),
        ),
        migrations.AlterField(
            model_name='waste',
            name='latitude',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='waste',
            name='longitude',
            field=models.CharField(default='', max_length=256),
        ),
    ]
