# Generated by Django 4.2.2 on 2023-06-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_info.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('schedule_for', models.DateTimeField()),
                ('related_actor', models.CharField(choices=[('D', 'Driver'), ('S', 'System')], default='D', max_length=1)),
                ('schedule_at', models.DateTimeField(auto_now=True)),
                ('schedule_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.collectionroute')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=100)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_info.municipality')),
            ],
        ),
    ]
