# Generated by Django 4.2.2 on 2023-06-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='collection_route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.collectionroute'),
            preserve_default=False,
        ),
    ]
