# Generated by Django 4.2.2 on 2023-06-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_collectionpoint_collection_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpoint',
            name='municipality',
        ),
    ]
