# Generated by Django 4.2.2 on 2023-06-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_info', '0003_alter_district_province_alter_municipality_district'),
        ('schedule', '0003_remove_collectionpoint_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='collection_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.collectionroute'),
        ),
        migrations.AlterField(
            model_name='collectionroute',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country_info.municipality'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.collectionroute'),
        ),
    ]
