# Generated by Django 4.2.2 on 2023-06-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_userviewedschedule_delete_scheduleuserviewstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_to',
            new_name='collection_route',
        ),
    ]
