# Generated by Django 4.2.2 on 2023-09-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_rename_schedule_to_schedule_collection_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
