# Generated by Django 4.2.2 on 2023-10-01 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.file_rename


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0009_alter_collectionpoint_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.file_rename.File.rename)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('schedule_for', models.DateTimeField()),
                ('collection_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.collectionroute')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
